
language: python

install:
  - pip install ansible ansible-lint

script:
  - ansible-lint install.yml  
  - ansible-playbook -i inventory --limit test install.yml --check
  - ansible-playbook -i inventory --limit test install.yml 
  - ansible-playbook -i inventory install.yml --check

deploy:
  - provider: script 
    script: ansible-playbook -i inventory install.yml 
    on: 
      branch: master

