
# References
# - https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# - https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis

language: python
python: 3.7
services:
  - docker

install:
  - pip install ansible ansible-lint

# Lint playbooks & run on test servers
script:
  - cd deploying-dokuwiki 
  - ansible-lint install.yml  
  - ansible-playbook -i inventory --limit test install.yml 
  - cd deploying-docker-compose
  - ansible-lint install.yml  
  - ansible-playbook -i inventory --limit test install.yml 

# Run on real servers on master branch
deploy:
  - provider: script 
    script: 
      - ansible-playbook -i inventory install.yml 
    on: 
      branch: master

