
# References
# - https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# - https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis

services:
  - docker

install:
  - docker pull python:3.7-buster
  - cd .travis
  - docker-compose run --rm --name control -it python:3.7-buster -d yes >/dev/null
  - docker-compose run --rm --name server0 -it python:3.7-buster -d yes >/dev/null
  - docker-compose run --rm --name server1 -it python:3.7-buster -d yes >/dev/null
  - docker-compose run --rm --name server2 -it python:3.7-buster -d yes >/dev/null
  - docker exec -it control apt-get update
  - docker exec -it control apt-get install -y python3-pip
  - docker exec -it control pip3 install ansible ansible-lint

# Lint playbooks & run on test servers
script:
  - cd deploying-dokuwiki 
  - ansible-lint install.yml  
  - ansible-playbook -i inventory --limit test install.yml 
  - cd deploying-docker-compose
  - ansible-lint install.yml  
  - ansible-playbook -i inventory --limit test install.yml 

# Run on real servers on master branch
deploy:
  - provider: script 
    script: 
      - ansible-playbook -i inventory install.yml 
    on: 
      branch: master

