
# References
# - https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# - https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis

services:
  - docker

install:
  - docker pull python:3.7-buster
  - cd .travis
  - docker network create travis
  - docker run --rm --network travis --name control -d -it python:3.7-buster yes >/dev/null
  - docker run --rm --network travis --name server0 -d -it python:3.7-buster yes >/dev/null
  - docker run --rm --network travis --name server1 -d -it python:3.7-buster yes >/dev/null
  - docker run --rm --network travis --name server2 -d -it python:3.7-buster yes >/dev/null
  - docker exec -it control pip3 install ansible ansible-lint

# Lint playbooks & run on test servers
script:
  - docker cp deploying-dokuwiki control:/app
  - docker exec -it control bash -c 'cd /app && ansible-lint install.yml'
  - docker exec -it control bash -c 'cd /app && ansible-playbook -i inventory install.yml'

# Run on real servers on master branch
deploy:
  - provider: script 
    script: 
      - ansible-playbook -i inventory install.yml 
    on: 
      branch: master

