---
- hosts: all
  tasks:
    - name: Install vim everywhere :-]
      apt: 
        name: vim
        state: present

- hosts: app
  tasks:
    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
    - name: Clone git repository
      git: 
        repo: 'https://github.com/Dream-Team-of-Sab/projet-coloc'
        dest: /usr/src/projet-coloc
        version: dev
    - name: Pull docker base image
      shell: docker pull python:3.7-buster
    - name: Build docker image
      shell: docker-compose build -d app
      args:
        chdir: /usr/src/projet-coloc
    - name: Run docker-compose
      shell: docker-compose up -d app
      args:
        chdir: /usr/src/projet-coloc

- hosts: proxy
  tasks:
    - name: Install haproxy server
      apt:
        name: haproxy
        state: present
    - name: Copy haproxy configuration
      copy:
        src: proxy/etc.haproxy.haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

- hosts: db
  tasks:
    - name: Install the postgresql server
      apt:
        name: postgresql
        state: present
    - name: Install the postgresql client
      apt:
        name: postgresql-client
        state: present
